package Arithmetic;


/**
* Arithmetic/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arithmetic.idl
* Wednesday, 15 November, 2023 5:52:42 PM IST
*/

public interface CalculatorOperations 
{
  double add (double a, double b);
  double subtract (double a, double b);
  double multiply (double a, double b);
  double divide (double a, double b);
} // interface CalculatorOperations
