package Arithmetic;


/**
* Arithmetic/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arithmetic.idl
* Wednesday, 15 November, 2023 5:52:42 PM IST
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
