package Arithmetic;

/**
* Arithmetic/CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arithmetic.idl
* Wednesday, 15 November, 2023 5:52:42 PM IST
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public Arithmetic.Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (Arithmetic.Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Arithmetic.CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Arithmetic.CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Arithmetic.CalculatorHelper.type ();
  }

}
