package HelloWorldApp;


/**
* HelloWorldApp/HelloWorldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* Wednesday, 15 November, 2023 2:14:50 PM IST
*/

public interface HelloWorldOperations 
{
  String sayHello ();
} // interface HelloWorldOperations
