package HelloWorldApp;

/**
* HelloWorldApp/HelloWorldHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* Wednesday, 15 November, 2023 2:14:50 PM IST
*/

public final class HelloWorldHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloWorldApp.HelloWorld value = null;

  public HelloWorldHolder ()
  {
  }

  public HelloWorldHolder (HelloWorldApp.HelloWorld initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloWorldApp.HelloWorldHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloWorldApp.HelloWorldHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloWorldApp.HelloWorldHelper.type ();
  }

}
